// OpsFlow 360 – Permission Codes & Role Mapping

import { Role, RoleType, Permission } from '../../types';

export const PERMISSION_CODES = {
  // Auth
  AUTH_LOGIN: 'auth.login',
  AUTH_LOGOUT: 'auth.logout',
  AUTH_REFRESH: 'auth.refresh',

  // Interbank
  INTERBANK_CREATE: 'payment.interbank.create',
  INTERBANK_VIEW_OWN: 'payment.interbank.view_own',
  INTERBANK_VIEW_DEPT: 'payment.interbank.view_department',
  INTERBANK_VIEW_ALL: 'payment.interbank.view_all',
  INTERBANK_REVIEW: 'payment.interbank.review',
  INTERBANK_APPROVE: 'payment.interbank.approve',
  INTERBANK_REJECT: 'payment.interbank.reject',
  INTERBANK_CANCEL: 'payment.interbank.cancel',
  INTERBANK_START_PROCESSING: 'payment.interbank.start_processing',
  INTERBANK_COMPLETE: 'payment.interbank.complete',
  INTERBANK_EXPORT: 'payment.interbank.export',

  // Beneficiary
  BENEFICIARY_CREATE: 'beneficiary.create',
  BENEFICIARY_VIEW_OWN: 'beneficiary.view_own',
  BENEFICIARY_VIEW_ALL: 'beneficiary.view_all',
  BENEFICIARY_REVIEW: 'beneficiary.review',
  BENEFICIARY_APPROVE: 'beneficiary.approve',
  BENEFICIARY_REJECT: 'beneficiary.reject',
  BENEFICIARY_START_ENTRY: 'beneficiary.start_entry',
  BENEFICIARY_COMPLETE_ENTRY: 'beneficiary.complete_entry',
  BENEFICIARY_MARK_FAILED: 'beneficiary.mark_failed',
  BENEFICIARY_EXPORT: 'beneficiary.export',

  // Vendor Payment
  VENDOR_PAYMENT_CREATE: 'vendor_payment.create',
  VENDOR_PAYMENT_VIEW_OWN: 'vendor_payment.view_own',
  VENDOR_PAYMENT_VIEW_DEPT: 'vendor_payment.view_department',
  VENDOR_PAYMENT_VIEW_ALL: 'vendor_payment.view_all',
  VENDOR_PAYMENT_REVIEW: 'vendor_payment.review',
  VENDOR_PAYMENT_APPROVE: 'vendor_payment.approve',
  VENDOR_PAYMENT_REJECT: 'vendor_payment.reject',
  VENDOR_PAYMENT_CANCEL: 'vendor_payment.cancel',
  VENDOR_PAYMENT_START_PAYMENT_ENTRY: 'vendor_payment.start_payment_entry',
  VENDOR_PAYMENT_COMPLETE_PAYMENT_ENTRY: 'vendor_payment.complete_payment_entry',
  VENDOR_PAYMENT_MARK_PAID: 'vendor_payment.mark_paid',
  VENDOR_PAYMENT_MARK_FAILED: 'vendor_payment.mark_failed',
  VENDOR_PAYMENT_MARK_REVERSED: 'vendor_payment.mark_reversed',
  VENDOR_PAYMENT_EXPORT: 'vendor_payment.export',

  // System
  AUDIT_VIEW: 'payment.audit.view',
  REPORTS_VIEW: 'payment.reports.view',
  SETTINGS_MANAGE: 'payment.settings.manage',
  USERS_MANAGE: 'payment.users.manage',
  ROLES_MANAGE: 'payment.roles.manage',
  PERMISSIONS_MANAGE: 'payment.permissions.manage',
  STATUS_OVERRIDE: 'payment.status_override',
} as const;

export const ALL_PERMISSIONS: Permission[] = [
  { code: PERMISSION_CODES.AUTH_LOGIN, name: 'Login', module: 'auth', description: 'Log in to the system' },
  { code: PERMISSION_CODES.AUTH_LOGOUT, name: 'Logout', module: 'auth', description: 'Log out of system' },
  { code: PERMISSION_CODES.AUTH_REFRESH, name: 'Refresh Token', module: 'auth', description: 'Refresh JWT token' },

  { code: PERMISSION_CODES.INTERBANK_CREATE, name: 'Create Interbank Request', module: 'interbank', description: 'Submit interbank transfer requests' },
  { code: PERMISSION_CODES.INTERBANK_VIEW_OWN, name: 'View Own Interbank Requests', module: 'interbank', description: 'View own submitted interbank requests' },
  { code: PERMISSION_CODES.INTERBANK_VIEW_DEPT, name: 'View Department Interbank Requests', module: 'interbank', description: 'View department interbank requests' },
  { code: PERMISSION_CODES.INTERBANK_VIEW_ALL, name: 'View All Interbank Requests', module: 'interbank', description: 'View all interbank requests across enterprise' },
  { code: PERMISSION_CODES.INTERBANK_REVIEW, name: 'Review Interbank Request', module: 'interbank', description: 'Review and request clarifications' },
  { code: PERMISSION_CODES.INTERBANK_APPROVE, name: 'Approve Interbank Request', module: 'interbank', description: 'Approve interbank transfer requests' },
  { code: PERMISSION_CODES.INTERBANK_REJECT, name: 'Reject Interbank Request', module: 'interbank', description: 'Reject interbank transfer with mandatory reason' },
  { code: PERMISSION_CODES.INTERBANK_CANCEL, name: 'Cancel Interbank Request', module: 'interbank', description: 'Cancel interbank transfer request' },
  { code: PERMISSION_CODES.INTERBANK_START_PROCESSING, name: 'Start Interbank Processing', module: 'interbank', description: 'Initiate processing of approved transfer' },
  { code: PERMISSION_CODES.INTERBANK_COMPLETE, name: 'Complete Interbank Transfer', module: 'interbank', description: 'Mark transfer complete with reference' },
  { code: PERMISSION_CODES.INTERBANK_EXPORT, name: 'Export Interbank Data', module: 'interbank', description: 'Export interbank transfers to Excel/CSV' },

  { code: PERMISSION_CODES.BENEFICIARY_CREATE, name: 'Create Beneficiary', module: 'beneficiary', description: 'Submit new beneficiary addition request' },
  { code: PERMISSION_CODES.BENEFICIARY_VIEW_OWN, name: 'View Own Beneficiaries', module: 'beneficiary', description: 'View own submitted beneficiary requests' },
  { code: PERMISSION_CODES.BENEFICIARY_VIEW_ALL, name: 'View All Beneficiaries', module: 'beneficiary', description: 'View all beneficiary records' },
  { code: PERMISSION_CODES.BENEFICIARY_REVIEW, name: 'Review Beneficiary', module: 'beneficiary', description: 'Review beneficiary details' },
  { code: PERMISSION_CODES.BENEFICIARY_APPROVE, name: 'Approve Beneficiary', module: 'beneficiary', description: 'Approve beneficiary addition' },
  { code: PERMISSION_CODES.BENEFICIARY_REJECT, name: 'Reject Beneficiary', module: 'beneficiary', description: 'Reject beneficiary with mandatory reason' },
  { code: PERMISSION_CODES.BENEFICIARY_START_ENTRY, name: 'Start Beneficiary Entry', module: 'beneficiary', description: 'Begin bank portal entry' },
  { code: PERMISSION_CODES.BENEFICIARY_COMPLETE_ENTRY, name: 'Complete Beneficiary Entry', module: 'beneficiary', description: 'Mark beneficiary addition as done in bank' },
  { code: PERMISSION_CODES.BENEFICIARY_MARK_FAILED, name: 'Mark Beneficiary Failed', module: 'beneficiary', description: 'Mark beneficiary addition failed' },
  { code: PERMISSION_CODES.BENEFICIARY_EXPORT, name: 'Export Beneficiaries', module: 'beneficiary', description: 'Export beneficiaries to Excel/CSV' },

  { code: PERMISSION_CODES.VENDOR_PAYMENT_CREATE, name: 'Create Vendor Payment', module: 'vendor_payment', description: 'Submit vendor payment request' },
  { code: PERMISSION_CODES.VENDOR_PAYMENT_VIEW_OWN, name: 'View Own Vendor Payments', module: 'vendor_payment', description: 'View own submitted vendor payments' },
  { code: PERMISSION_CODES.VENDOR_PAYMENT_VIEW_DEPT, name: 'View Dept Vendor Payments', module: 'vendor_payment', description: 'View department vendor payments' },
  { code: PERMISSION_CODES.VENDOR_PAYMENT_VIEW_ALL, name: 'View All Vendor Payments', module: 'vendor_payment', description: 'View all vendor payments' },
  { code: PERMISSION_CODES.VENDOR_PAYMENT_REVIEW, name: 'Review Vendor Payment', module: 'vendor_payment', description: 'Review payment request details' },
  { code: PERMISSION_CODES.VENDOR_PAYMENT_APPROVE, name: 'Approve Vendor Payment', module: 'vendor_payment', description: 'Approve vendor payment request' },
  { code: PERMISSION_CODES.VENDOR_PAYMENT_REJECT, name: 'Reject Vendor Payment', module: 'vendor_payment', description: 'Reject vendor payment with reason' },
  { code: PERMISSION_CODES.VENDOR_PAYMENT_CANCEL, name: 'Cancel Vendor Payment', module: 'vendor_payment', description: 'Cancel vendor payment request' },
  { code: PERMISSION_CODES.VENDOR_PAYMENT_START_PAYMENT_ENTRY, name: 'Start Payment Entry', module: 'vendor_payment', description: 'Begin bank payment entry' },
  { code: PERMISSION_CODES.VENDOR_PAYMENT_COMPLETE_PAYMENT_ENTRY, name: 'Complete Payment Entry', module: 'vendor_payment', description: 'Mark payment entry done' },
  { code: PERMISSION_CODES.VENDOR_PAYMENT_MARK_PAID, name: 'Mark Paid', module: 'vendor_payment', description: 'Mark payment verified and paid with ref/proof' },
  { code: PERMISSION_CODES.VENDOR_PAYMENT_MARK_FAILED, name: 'Mark Failed', module: 'vendor_payment', description: 'Mark payment attempt failed' },
  { code: PERMISSION_CODES.VENDOR_PAYMENT_MARK_REVERSED, name: 'Mark Reversed', module: 'vendor_payment', description: 'Mark transaction reversed' },
  { code: PERMISSION_CODES.VENDOR_PAYMENT_EXPORT, name: 'Export Vendor Payments', module: 'vendor_payment', description: 'Export vendor payment data' },

  { code: PERMISSION_CODES.AUDIT_VIEW, name: 'View Audit Logs', module: 'audit', description: 'Access immutable audit trail' },
  { code: PERMISSION_CODES.REPORTS_VIEW, name: 'View Reports', module: 'reports', description: 'Access reports & analytics' },
  { code: PERMISSION_CODES.SETTINGS_MANAGE, name: 'Manage Settings', module: 'system', description: 'Manage workflow and system settings' },
  { code: PERMISSION_CODES.USERS_MANAGE, name: 'Manage Users', module: 'system', description: 'Create and update user accounts' },
  { code: PERMISSION_CODES.ROLES_MANAGE, name: 'Manage Roles', module: 'system', description: 'Configure role definitions' },
  { code: PERMISSION_CODES.PERMISSIONS_MANAGE, name: 'Manage Permissions', module: 'system', description: 'Assign permissions to roles' },
  { code: PERMISSION_CODES.STATUS_OVERRIDE, name: 'Status Override', module: 'system', description: 'Super Admin emergency status override with reason' },
];

export const ROLE_DEFINITIONS: Record<RoleType, Role> = {
  SUPER_ADMIN: {
    id: 'role-super-admin',
    name: 'Super Admin',
    code: 'SUPER_ADMIN',
    description: 'Full system access, user management, status overrides, and audit trails',
    isSystem: true,
    permissions: ALL_PERMISSIONS.map(p => p.code),
  },

  MANAGEMENT_VIEWER: {
    id: 'role-management-viewer',
    name: 'Management Viewer',
    code: 'MANAGEMENT_VIEWER',
    description: 'Read-only dashboard, reports, and payment status visibility without editing rights',
    isSystem: true,
    permissions: [
      PERMISSION_CODES.AUTH_LOGIN,
      PERMISSION_CODES.AUTH_LOGOUT,
      PERMISSION_CODES.AUTH_REFRESH,
      PERMISSION_CODES.INTERBANK_VIEW_ALL,
      PERMISSION_CODES.BENEFICIARY_VIEW_ALL,
      PERMISSION_CODES.VENDOR_PAYMENT_VIEW_ALL,
      PERMISSION_CODES.REPORTS_VIEW,
      PERMISSION_CODES.INTERBANK_EXPORT,
      PERMISSION_CODES.BENEFICIARY_EXPORT,
      PERMISSION_CODES.VENDOR_PAYMENT_EXPORT,
    ],
  },

  EMPLOYEE_REQUESTER: {
    id: 'role-employee-requester',
    name: 'Employee / Requester',
    code: 'EMPLOYEE_REQUESTER',
    description: 'Create interbank, beneficiary, and vendor payment requests and view own submitted requests',
    isSystem: true,
    permissions: [
      PERMISSION_CODES.AUTH_LOGIN,
      PERMISSION_CODES.AUTH_LOGOUT,
      PERMISSION_CODES.AUTH_REFRESH,
      PERMISSION_CODES.INTERBANK_CREATE,
      PERMISSION_CODES.INTERBANK_VIEW_OWN,
      PERMISSION_CODES.BENEFICIARY_CREATE,
      PERMISSION_CODES.BENEFICIARY_VIEW_OWN,
      PERMISSION_CODES.VENDOR_PAYMENT_CREATE,
      PERMISSION_CODES.VENDOR_PAYMENT_VIEW_OWN,
    ],
  },

  DEPARTMENT_MANAGER: {
    id: 'role-dept-manager',
    name: 'Department Manager',
    code: 'DEPARTMENT_MANAGER',
    description: 'View and review requests for assigned department, approve/reject if delegated',
    isSystem: true,
    permissions: [
      PERMISSION_CODES.AUTH_LOGIN,
      PERMISSION_CODES.AUTH_LOGOUT,
      PERMISSION_CODES.AUTH_REFRESH,
      PERMISSION_CODES.INTERBANK_VIEW_DEPT,
      PERMISSION_CODES.INTERBANK_VIEW_OWN,
      PERMISSION_CODES.INTERBANK_REVIEW,
      PERMISSION_CODES.INTERBANK_APPROVE,
      PERMISSION_CODES.INTERBANK_REJECT,
      PERMISSION_CODES.BENEFICIARY_VIEW_ALL,
      PERMISSION_CODES.BENEFICIARY_REVIEW,
      PERMISSION_CODES.BENEFICIARY_APPROVE,
      PERMISSION_CODES.BENEFICIARY_REJECT,
      PERMISSION_CODES.VENDOR_PAYMENT_VIEW_DEPT,
      PERMISSION_CODES.VENDOR_PAYMENT_VIEW_OWN,
      PERMISSION_CODES.VENDOR_PAYMENT_REVIEW,
      PERMISSION_CODES.VENDOR_PAYMENT_APPROVE,
      PERMISSION_CODES.VENDOR_PAYMENT_REJECT,
      PERMISSION_CODES.REPORTS_VIEW,
    ],
  },

  FINANCE_APPROVER: {
    id: 'role-finance-approver',
    name: 'Finance Approver',
    code: 'FINANCE_APPROVER',
    description: 'Review requests enterprise-wide, approve, reject, add financial review remarks',
    isSystem: true,
    permissions: [
      PERMISSION_CODES.AUTH_LOGIN,
      PERMISSION_CODES.AUTH_LOGOUT,
      PERMISSION_CODES.AUTH_REFRESH,
      PERMISSION_CODES.INTERBANK_VIEW_ALL,
      PERMISSION_CODES.INTERBANK_REVIEW,
      PERMISSION_CODES.INTERBANK_APPROVE,
      PERMISSION_CODES.INTERBANK_REJECT,
      PERMISSION_CODES.INTERBANK_EXPORT,
      PERMISSION_CODES.BENEFICIARY_VIEW_ALL,
      PERMISSION_CODES.BENEFICIARY_REVIEW,
      PERMISSION_CODES.BENEFICIARY_APPROVE,
      PERMISSION_CODES.BENEFICIARY_REJECT,
      PERMISSION_CODES.BENEFICIARY_EXPORT,
      PERMISSION_CODES.VENDOR_PAYMENT_VIEW_ALL,
      PERMISSION_CODES.VENDOR_PAYMENT_REVIEW,
      PERMISSION_CODES.VENDOR_PAYMENT_APPROVE,
      PERMISSION_CODES.VENDOR_PAYMENT_REJECT,
      PERMISSION_CODES.VENDOR_PAYMENT_EXPORT,
      PERMISSION_CODES.REPORTS_VIEW,
    ],
  },

  BENEFICIARY_ENTRY_USER: {
    id: 'role-beneficiary-entry-user',
    name: 'Beneficiary Entry User',
    code: 'BENEFICIARY_ENTRY_USER',
    description: 'View approved beneficiary requests, initiate entry in bank portal, mark done or failed',
    isSystem: true,
    permissions: [
      PERMISSION_CODES.AUTH_LOGIN,
      PERMISSION_CODES.AUTH_LOGOUT,
      PERMISSION_CODES.AUTH_REFRESH,
      PERMISSION_CODES.BENEFICIARY_VIEW_ALL,
      PERMISSION_CODES.BENEFICIARY_START_ENTRY,
      PERMISSION_CODES.BENEFICIARY_COMPLETE_ENTRY,
      PERMISSION_CODES.BENEFICIARY_MARK_FAILED,
      PERMISSION_CODES.BENEFICIARY_EXPORT,
      PERMISSION_CODES.REPORTS_VIEW,
    ],
  },

  PAYMENT_ENTRY_USER: {
    id: 'role-payment-entry-user',
    name: 'Payment Entry User',
    code: 'PAYMENT_ENTRY_USER',
    description: 'View approved vendor payments & interbank requests, start processing, enter payment details',
    isSystem: true,
    permissions: [
      PERMISSION_CODES.AUTH_LOGIN,
      PERMISSION_CODES.AUTH_LOGOUT,
      PERMISSION_CODES.AUTH_REFRESH,
      PERMISSION_CODES.INTERBANK_VIEW_ALL,
      PERMISSION_CODES.INTERBANK_START_PROCESSING,
      PERMISSION_CODES.INTERBANK_COMPLETE,
      PERMISSION_CODES.VENDOR_PAYMENT_VIEW_ALL,
      PERMISSION_CODES.VENDOR_PAYMENT_START_PAYMENT_ENTRY,
      PERMISSION_CODES.VENDOR_PAYMENT_COMPLETE_PAYMENT_ENTRY,
      PERMISSION_CODES.VENDOR_PAYMENT_EXPORT,
      PERMISSION_CODES.REPORTS_VIEW,
    ],
  },

  PAYMENT_VERIFIER: {
    id: 'role-payment-verifier',
    name: 'Payment Verifier',
    code: 'PAYMENT_VERIFIER',
    description: 'Verify payment completion, mark paid with bank reference or proof, mark failed or reversed',
    isSystem: true,
    permissions: [
      PERMISSION_CODES.AUTH_LOGIN,
      PERMISSION_CODES.AUTH_LOGOUT,
      PERMISSION_CODES.AUTH_REFRESH,
      PERMISSION_CODES.INTERBANK_VIEW_ALL,
      PERMISSION_CODES.INTERBANK_COMPLETE,
      PERMISSION_CODES.VENDOR_PAYMENT_VIEW_ALL,
      PERMISSION_CODES.VENDOR_PAYMENT_MARK_PAID,
      PERMISSION_CODES.VENDOR_PAYMENT_MARK_FAILED,
      PERMISSION_CODES.VENDOR_PAYMENT_MARK_REVERSED,
      PERMISSION_CODES.VENDOR_PAYMENT_EXPORT,
      PERMISSION_CODES.REPORTS_VIEW,
    ],
  },

  AUDITOR_VIEWER: {
    id: 'role-auditor-viewer',
    name: 'Auditor / Viewer',
    code: 'AUDITOR_VIEWER',
    description: 'Read-only access to selected financial records and complete immutable audit logs',
    isSystem: true,
    permissions: [
      PERMISSION_CODES.AUTH_LOGIN,
      PERMISSION_CODES.AUTH_LOGOUT,
      PERMISSION_CODES.AUTH_REFRESH,
      PERMISSION_CODES.INTERBANK_VIEW_ALL,
      PERMISSION_CODES.BENEFICIARY_VIEW_ALL,
      PERMISSION_CODES.VENDOR_PAYMENT_VIEW_ALL,
      PERMISSION_CODES.AUDIT_VIEW,
      PERMISSION_CODES.REPORTS_VIEW,
      PERMISSION_CODES.INTERBANK_EXPORT,
      PERMISSION_CODES.BENEFICIARY_EXPORT,
      PERMISSION_CODES.VENDOR_PAYMENT_EXPORT,
    ],
  },
};
